artifact_paths_template: &a_p_t
  artifact_paths: '**/test-results/**/*.xml'

steps:
  - name: Run Tests - Suite 1
    command: "./gradlew testReleaseUnitTest --tests se.paldan.helloworld.ExampleUnitTest"
    <<: *a_p_t
  - name: Run Tests - Suite 2
    command: "./gradlew testReleaseUnitTest --tests se.paldan.helloworld.ExampleUnitTestTwo"
    <<: *a_p_t
  - name: Run Tests - Suite 3
    command: "./gradlew testReleaseUnitTest --tests se.paldan.helloworld.ExampleUnitTestThree"
    <<: *a_p_t
  - name: Run Tests - Suite 4
    command: "./gradlew testReleaseUnitTest --tests se.paldan.helloworld.ExampleUnitTestFour"
    <<: *a_p_t
  - name: Run Tests - Suite 5
    command: "./gradlew testReleaseUnitTest --tests se.paldan.helloworld.ExampleUnitTestFive"
    <<: *a_p_t
